### PR TITLE
Send a different email when signing up again

### PR DESCRIPTION
**Pull request by jacebrowning**
This will allow someone to run through the signup flow twice.

### CODE REVIEW

**Comment by jacebrowning** [comment]
Hmm... this results in two emails being sent when signing up. I'll take this a queue to split signup into a separate route.

**Comment by jacebrowning** [comment]
Alright @diiq I'm stuck. I cannot figure out why the frontend is making two POSTs to `/api/voters/`.

1. Go to https://voter-engagement-staging-pr-33.herokuapp.com/registration-verified
2. Open your network tab
3. Submit the form with foobar@example.com

**Comment by diiq** [comment]
@jacebrowning The form element had an onSubmit action AND the button had the same action. Clicking the button both, uh, clicked the button AND submitted the form.

Added a one-liner commit that should resolve the issue.

**Comment by diiq** [comment]
That said, I'm getting a 500 from the server on that request, but the payload looks right to me, so I'm passing it back to you.

**Comment by jacebrowning** [comment]
A 500 locally is likely missing credentials for SendGrid. I think this is now working as expected. Thanks!

**Pull request merged**
